apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  CLUSTER_URL: mongodb+srv://ericwong3:2K57BU6A8f4vw2nD@cluster0.51rghfw.mongodb.net/sample?retryWrites=true&w=majority
